#Source: https://github.com/vatsal220/medium_articles/blob/main/active_learning/active.ipynb

# low predictions with threshold <= 0.6
low_th=0.6

# high predictions with threshold >= 0.9
high_th=0.9


def check_preds(pred_dct, low_th=low_th, high_th=high_th):
    '''
    This function will check the dictionary associated to the prediction probabilities
    generated by the model. It will return either `annotate`, `annotated` or `neither`
    as a result.

    params:
        pred_dct (Dictionary) : The keys are the classes, values are the predicted proba
        low_th (Integer) : The low prediction proba threshold
        high_th (Integer): The high prediction proba threshold

    returns:
        This function will return the following:
            `annotate` : if the maximum value in the pred_dct is less than or equal to
                         the low_th
            `annotated` : if the maximum value in the pred_dct is greater than or equal to
                          the high_th
            'neither' : If it does not fall in the other two ranges

    example:
        pred_df['annotate_decision'] = pred_df['pred_proba'].apply(check_preds)
    '''

    max_val=max( list( pred_dct.values() ) )
    if max_val <= low_th:
        return 'annotate'
    elif max_val >= high_th:
        return 'annotated'
    else:
        return 'neither'